/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package InterfazGrafica;

import stack.Consumidor;
import stack.PilaLenta;
import stack.Productor;

/**
 *
 * @author rubco
 */
public class PilaFrame extends java.awt.Frame {

    /**
     * Creates new form PilaFrame
     */
    public PilaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        int alto = 600;
        int ancho = 600;
        int capacidad_pila = 8;

        PilaFrame f = new PilaFrame();

        f.setTitle("Pila lenta");
        f.setSize(ancho, alto);
        f.setVisible(true);
        f.setLocationRelativeTo(null);

        CanvasPila cv = new CanvasPila(ancho, alto);
        f.add(cv);
        PilaLenta pila = new PilaLenta(capacidad_pila, cv);

        Productor p0 = new Productor(pila, cv, 0);
        Productor p1 = new Productor(pila, cv, 1);
        Productor p2 = new Productor(pila, cv, 2);
        Productor p3 = new Productor(pila, cv, 3);
        Thread h1 = new Thread(new Consumidor(pila, cv));

        h1.start();
        p0.start();
        p1.start();
        p2.start();
        p3.start();
        
        try {
            h1.join();
            p0.join();
            p1.join();
            p2.join();
            p3.join();
            pila.finalizarNotificar();
        } catch (InterruptedException e) {
            System.out.println("Error de join: " + e.getMessage());
        }

        f.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
